name: deploy-docker-lab

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: milydemendoza/php-sample-app-lab
  IMAGE_TAG: "1.0.0"
  GIT_USER_EMAIL: "milydemendoza@gmail.com"
  GIT_USER_NAME: "milymoreno"

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
